# Generated by Django 5.1.4 on 2025-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detalles', models.TextField()),
                ('periodo', models.CharField(choices=[('dia', 'Dia'), ('semana', 'Semana'), ('mes', 'Mes'), ('año', 'Año')], max_length=6)),
                ('eventos', models.IntegerField()),
                ('icono', models.TextField(null=True)),
                ('meta', models.IntegerField(null=True)),
                ('plazo', models.DateField()),
                ('completado', models.IntegerField(default=0)),
                ('cuenta_id', models.IntegerField(null=True)),
            ],
        ),
    ]
