# Generated by Django 5.1.4 on 2025-01-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
